//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BallHitBrick {
            get {
                return ResourceManager.GetStream("BallHitBrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ballSprite {
            get {
                object obj = ResourceManager.GetObject("ballSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap big_stretch_pog {
            get {
                object obj = ResourceManager.GetObject("big_stretch_pog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueBrick {
            get {
                object obj = ResourceManager.GetObject("blueBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap coldcoldocldoclo {
            get {
                object obj = ResourceManager.GetObject("coldcoldocldoclo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Double_Points_PowerUp {
            get {
                object obj = ResourceManager.GetObject("Double_Points_PowerUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DoublePoints_PowerUP {
            get {
                return ResourceManager.GetStream("DoublePoints PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap douvle {
            get {
                object obj = ResourceManager.GetObject("douvle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exitButtonSprite {
            get {
                object obj = ResourceManager.GetObject("exitButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exitSettingsButtonSprite {
            get {
                object obj = ResourceManager.GetObject("exitSettingsButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fire_Anti_PowerUp {
            get {
                object obj = ResourceManager.GetObject("Fire_Anti_PowerUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Fire_PowerUP {
            get {
                return ResourceManager.GetStream("Fire PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fullscreenButtonSprite {
            get {
                object obj = ResourceManager.GetObject("fullscreenButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gameoverTitleSprite {
            get {
                object obj = ResourceManager.GetObject("gameoverTitleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenBrick {
            get {
                object obj = ResourceManager.GetObject("greenBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;HighScore&gt;
        ///  &lt;Score&gt;
        ///    &lt;numericScore&gt;100&lt;/numericScore&gt;
        ///    &lt;name&gt;Jms&lt;/name&gt;
        ///    &lt;date&gt;20/10/2020&lt;/date&gt;
        ///  &lt;/Score&gt;
        ///  &lt;Score&gt;
        ///    &lt;numericScore&gt;800&lt;/numericScore&gt;
        ///    &lt;name&gt;Jsn&lt;/name&gt;
        ///    &lt;date&gt;20/11/2020&lt;/date&gt;
        ///  &lt;/Score&gt;
        ///  &lt;Score&gt;
        ///    &lt;numericScore&gt;400&lt;/numericScore&gt;
        ///    &lt;name&gt;Sri&lt;/name&gt;
        ///    &lt;date&gt;20/9/2020&lt;/date&gt;
        ///  &lt;/Score&gt;
        ///&lt;/HighScore&gt;
        ///.
        /// </summary>
        internal static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoreBox {
            get {
                object obj = ResourceManager.GetObject("highscoreBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoresButtonSprite {
            get {
                object obj = ResourceManager.GetObject("highscoresButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoreTitleSprite {
            get {
                object obj = ResourceManager.GetObject("highscoreTitleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Ice_PowerUP {
            get {
                return ResourceManager.GetStream("Ice PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap instructionsBox {
            get {
                object obj = ResourceManager.GetObject("instructionsBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Length_PowerUP {
            get {
                return ResourceManager.GetStream("Length PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Level_9_background {
            get {
                object obj = ResourceManager.GetObject("Level_9_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level10 {
            get {
                return ResourceManager.GetString("level10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level11 {
            get {
                return ResourceManager.GetString("level11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level12 {
            get {
                return ResourceManager.GetString("level12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;-3&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;76&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;158&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;248&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;336&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;422&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;508&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		&lt;hp&gt;1&lt;/hp&gt;
        ///	&lt;/brick&gt;
        ///	&lt;brick&gt;
        ///		&lt;x&gt;596&lt;/x&gt;
        ///		&lt;y&gt;0&lt;/y&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level7 {
            get {
                return ResourceManager.GetString("level7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level8 {
            get {
                return ResourceManager.GetString("level8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///.
        /// </summary>
        internal static string level9 {
            get {
                return ResourceManager.GetString("level9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream menuSound {
            get {
                return ResourceManager.GetStream("menuSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Mirror_PowerUP {
            get {
                return ResourceManager.GetStream("Mirror PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap muteButtonSprite {
            get {
                object obj = ResourceManager.GetObject("muteButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangeBrick {
            get {
                object obj = ResourceManager.GetObject("orangeBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream PaddleHitBall {
            get {
                return ResourceManager.GetStream("PaddleHitBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkBrick {
            get {
                object obj = ResourceManager.GetObject("pinkBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playButtonSprite {
            get {
                object obj = ResourceManager.GetObject("playButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redBrick {
            get {
                object obj = ResourceManager.GetObject("redBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingsButtonSprite {
            get {
                object obj = ResourceManager.GetObject("settingsButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingsTitleSprite {
            get {
                object obj = ResourceManager.GetObject("settingsTitleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Shield_PowerUP {
            get {
                return ResourceManager.GetStream("Shield PowerUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shieldSprite {
            get {
                object obj = ResourceManager.GetObject("shieldSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign {
            get {
                object obj = ResourceManager.GetObject("sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sridhar {
            get {
                object obj = ResourceManager.GetObject("sridhar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titleSprite {
            get {
                object obj = ResourceManager.GetObject("titleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whiteBrick {
            get {
                object obj = ResourceManager.GetObject("whiteBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellowBrick {
            get {
                object obj = ResourceManager.GetObject("yellowBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
