//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickBreaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrickBreaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap ballSprite {
            get {
                object obj = ResourceManager.GetObject("ballSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap blueBrick {
            get {
                object obj = ResourceManager.GetObject("blueBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap exitButtonSprite {
            get {
                object obj = ResourceManager.GetObject("exitButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap greenBrick {
            get {
                object obj = ResourceManager.GetObject("greenBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>

        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoreBox {
            get {
                object obj = ResourceManager.GetObject("highscoreBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
                }
                }
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;HighScore&gt;
        ///  &lt;Score&gt;
        ///    &lt;numericScore&gt;100&lt;/numericScore&gt;
        ///    &lt;name&gt;James&lt;/name&gt;
        ///    &lt;date&gt;20/10/2020&lt;/date&gt;
        ///  &lt;/Score&gt;
        ///&lt;/HighScore&gt;
        ///.
        /// </summary>
        internal static string HighScore {
            get {
                return ResourceManager.GetString("HighScore", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap highscoresButtonSprite {
            get {
                object obj = ResourceManager.GetObject("highscoresButtonSprite", resourceCulture);
                }
                }

        internal static System.Drawing.Bitmap Level_1_background {
            get {
                object obj = ResourceManager.GetObject("Level_1_background", resourceCulture);

                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>

        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap highscoreTitleSprite {
            get {
                object obj = ResourceManager.GetObject("highscoreTitleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
                }
                }

        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;level&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;-7&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;47&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;101&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;155&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;209&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;263&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/brick&gt;
        ///  &lt;brick&gt;
        ///    &lt;x&gt;317&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);

            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orangeBrick {
            get {
                object obj = ResourceManager.GetObject("orangeBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap paddleSprite {
            get {
                object obj = ResourceManager.GetObject("paddleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pinkBrick {
            get {
                object obj = ResourceManager.GetObject("pinkBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap playButtonSprite {
            get {
                object obj = ResourceManager.GetObject("playButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap redBrick {
            get {
                object obj = ResourceManager.GetObject("redBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap settingsButtonSprite {
            get {
                object obj = ResourceManager.GetObject("settingsButtonSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titleSprite {
            get {
                object obj = ResourceManager.GetObject("titleSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>

        internal static System.Drawing.Bitmap yellowBrick {
            get {
                object obj = ResourceManager.GetObject("yellowBrick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
